### ISSUE TITLE
Post Install Class not executed after deployed  

### ISSUE THREAD

**Issue by raghava3107** [SalesforceFoundation/CumulusCI#129]
We are trying to deploy the PostinstallClass in Dev org through metadata using ANT and target "postDeploy" class is getting created but not executing the code.

Could you let me know how to solve the Issue.

**Comment by e02d96ec16** [comment]
If you deploy only the class, then it won't execute: the post install code executes automatically as the last step of a package installation (CumulusCI doesn't execute it).
If you want to execute the code of the post install class, you'll need to do it manually by instantiating the class and calling the relevant method.
Example:
```apex
PostinstallClass a = new PostinstallClass();
a.onInstall(null);
```
The argument taken is an `InstallContext`. I used NULL because in my case it doesn't need anything else (it just generates some records), but you may change it to whatever context fits your purpose.
See more: 
[InstallHandler interface](https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_install_handler.htm)
[How does a Post Install Script Work?](https://help.salesforce.com/apex/HTViewHelpDoc?id=apex_post_install_script_intro.htm&language=en)

I hope I understood your question/scenario correctly, and this will be helpful to you.

**Comment by jlantz** [comment]
Closing this to clear up the Issues for CumulusCI 2.  Of note is that in CumulusCI 2, this could be done with a subclass of `cumulusci.tasks.salesforce.BaseToolingApiTask` to run anonymous Apex.

The Ant targets are now removed from CumulusCI and no longer actively supported. The old Ant target based CumulusCI now lives in the legacy-1.0 branch. I'll try to review and accept pull requests on that branch but will not be actively developing against the Ant version going forward.

All development focus has shifted to CumulusCI 2 which now has feature parity with the Ant based CumulusCI along with far better configurability, access to all Salesforce API's, and encrypted OAuth toolbelt, and a single CLI cci with command help for a much better user experience.
