### ISSUE TITLE
Port to sfdx pilot

### ISSUE THREAD

**Issue by jlantz** [SalesforceFoundation/CumulusCI#237]
The SFDX pilot has a new CLI with some new commands and features available.

- Switch to using `sfdx` CLI instead of `heroku force:*`
- Change to use force:org:describe instead of force:org:open to get org credentials
- Pass access token and instance url as env vars in SalesforceDXTask

**Comment by cdcarter** [comment]
Some recent discoveries:

- org describe doesn't get a refreshed token - so that won't work. there's a W-number for the bug.
- there's no documented interface for setting the instance url as an envvar. instead you have to set it with a call to `sfdx force:config:set instanceUrl=...` 
- the access token is set with the `--target-username` arg on any call

**Comment by cdcarter** [comment]
I have an active issue with getting known access token credentials passed to the sfdx cli, convo happening on org62.

**Comment by cdcarter** [comment]
Though it's not yet documented, instance URL is passed on env var `SFDX_INSTANCE_URL`. I have not been able to get this working yet but a SFDX dev is working w/ me.

**Comment by cdcarter** [comment]
proposed new module cumulusci.tasks.sfdx

class BaseSFDXTask(Command) (calls sfdx binary without org)
class SFDXOrgTask(BaseSFDXTask) (passes an org username or alias to sfdx through a command line arg)
class SFDXKeychainOrgTask(SalesforceCommand,BaseSFDXTask) (passes SFDX_INSTANCE_URL and SFDX_USERNAME [an access token] via the environment by overriding _get_env)

now using subprocess.Popen instead of sarge

**Comment by davisagli** [comment]
CumulusCI 2 is using the new SFDX CLI.
