### ISSUE TITLE
Use CCI org name as scratch org alias when creating scratch orgs

### ISSUE THREAD

**Issue by dospromptman** [SalesforceFoundation/CumulusCI#313]
Sometimes I use sfdx directly to work with my scratch orgs, but that requires looking up the scratch org username using `cci org info` (or `sfdx force:org:list`) and copy/pasting the username as the `--targetusername` argument every time.

It would be awesome if CumulusCI passed along the org name to sfdx when creating the scratch org to use as the org alias (`sfdx force:org:create --setalias foo`).

Then I could use the same logical org name for both tools.

Example:

```
$ cci org scratch dev my-dev-org
$ cci org info my-dev-org # creates scratch org
$ sfdx force:data:soql:query --targetusername my-dev-org -q "SELECT Id FROM Contact"
```

**Comment by dospromptman** [comment]
It looks like extra arguments are passed along to `sfdx:org:create` anyhow, so I guess I could do something like `cci org scratch dev my-dev-org --setalias my-dev-org` to get the alias set at creation time... but I still think it'd be nice to have it passed along automatically.

**Comment by jlantz** [comment]
I've been wanting to add this feature since they started allowing you to set aliases but haven't gotten around to it.  One note is that the sfdx aliases are global rather than repo specific so the alias would need to be something like Cumulus__dev or HEDAP__beta where the cci org names are "dev" and "beta" in the Cumulus and HEDAP repositories respectively.

Another thing that will help with this is when I get the sfdx command wrapper task configured.  Ideally, you should be able to use cci to run arbitrary sfdx commands using cci's keychain.  If the main reason for wanting an alias is to be able to run sfdx commands against the org this might be the better fix.  I still think it's a good idea for cci to set sfdx aliases though.
