### ISSUE TITLE
Proper way of setting post-install script in a packaging org

### ISSUE THREAD

**Issue by tempflip** [SalesforceFoundation/CumulusCI#320]
I have a managed package. I'm pushing metadata update using the

`cci task run deploy --org master` command (master is my packaging org).

This is my `cumulusci.yml` setup:

```
project:
    name: billing360
    package:
        name: billing360
        namespace: billing360
        install_class : bt_installHandler
    git:
        default_branch: dev-main
```

What is happening that the properly set up post-install script is nulled out in the packaging org. I've also tryed   `bt_installHandler.cls` and `billing360.bt_installHandler` -- the some result, no errors.

I've noticed that in the code the install_class is referenced on `PackageXmlGenerator` class in the `package.py`, however, when the class in initialized in `salesforce.py` nothing is passed as an `install_class` parameter (so it uses the default 'None' all the time).

Maybe it is a still missing feature? If not, any ideas how to set up a post-install script?

thanks,

**Comment by jlantz** [comment]
Use cci flow run ci_master --org master

The ci_master flow rebuilds the package.xml for deployment to the packaging org since that deployment is the only one where you're allowed to have an install or uninstall class specified in the package.xml.

You could recreate the same thing manually by running the tasks update_package_xml_managed and then deploy.

In general, if you're doing a deployment to an org you should try to use the out of the box flows provided with cumulusci.  Flow often have a very specific sequence of tasks necessary for a particular build operation like deploying a commit to packaging.
