### ISSUE TITLE
cci task run upload_beta initiates a Major Release

### ISSUE THREAD

**Issue by Szandor72** [SalesforceFoundation/CumulusCI#333]
I have made my tests fail in order to reproduce this.

`cci task run upload_beta -o name 'package'   --org packaging`

results in a major release in our current packaging org: 

![image](https://cloud.githubusercontent.com/assets/16804218/26695874/c5f9bc7e-470c-11e7-843f-ab580eb874d1.png)

Running `cci task run upload_beta -o name 'package'   -o production false --org packaging`  works as expected. 

![image](https://cloud.githubusercontent.com/assets/16804218/26696045/5958a3a4-470d-11e7-94f8-7935e0f12d5e.png)

**Comment by jlantz** [comment]
I'm a little stumped on this one.  We've been running the release_beta flow that calls upload_beta with no extra options since January without ever seeing this.  Reviewing the relevant code, it seems that it will default to production = False:

https://github.com/SalesforceFoundation/CumulusCI/blob/master/cumulusci/tasks/salesforce.py#L1114-L1119

Here's how the upload_beta task is defined in the cumulusci.yml:
https://github.com/SalesforceFoundation/CumulusCI/blob/master/cumulusci/cumulusci.yml#L209-L211

One possibility that might explain this.. Does this only occur when there's an Apex test failure?  I know the package upload UI has scared me a few times before thinking that it was uploading a production version when it was really uploading a beta.  It doesn't show that its a beta until the upload completes.

**Comment by Szandor72** [comment]
I think we should close this issue. I couldn't not reproduce it since the initial screenshot.
