### ISSUE TITLE
Way to install into scratch org when using Salesforce DX

### ISSUE THREAD

**Issue by keithmancuso** [SalesforceFoundation/CumulusCI#517]
Im starting to play with salesforce DX but Im not sure how i would go about installing NSPS into a scratch org? Is there any documentation about how to do this?

**Comment by jlantz** [comment]
Hi @keithmancuso Sorry for the delayed response on this.  I'm excited to hear from someone using CumulusCI for working with NPSP :)

The main instructions for setting up local builds of NPSP with cci are here:
http://developer.salesforce.org/Cumulus/Contributor/

However, those talk about how to use a DE org.  If you want to use scratch orgs, it's pretty simple if you already have CumulusCI and sfdx configured, connected to your devhub, and have the defaultdevhubusername configured (see sfdx force:config:list).  From there, just run this command from the NPSP repo (Cumulus):

`cci flow run dev_org --org dev`

That will spin up a scratch org from our included `dev` configuration for the project, deploy all NPSP dependencies, then deploy the unmanaged package code into the scratch org.  It'll then also deploy some configuration useful for development environments (dev_config) such as mapping layouts in the System Administrator profile.

If you need more info on setting up CumulusCI and sfdx, you can refer to the tutorial for CumulusCI.  If there's something confusing or not covered there, please let us know (or submit a doc contribution to the docs/ subfolder of this repo)

http://cumulusci.readthedocs.io/en/latest/tutorial.html

**Comment by jlantz** [comment]
One note: you won't be able to use the `dev_namespaced` scratch org definition since that requires registering the `npsp` namespace with your Salesforce DX devhub.  We can use that scratch profile internally as we own and have registered that namespace with our devhub, but since all of NPSP's code is designed to deploy cleanly in unmanaged or managed environments there's no need for a namespaced scratch org to do development.
