### ISSUE TITLE
Beta Tag does not get applied

### ISSUE THREAD

**Issue by Szandor72** [SalesforceFoundation/CumulusCI#520]
Our builds fail with error

`Release 1.0 (Beta 15) already exists at https://github.com/xxx/yyy/releases/tag/beta/1.0-Beta_15`

My Cumulus.yml indicates as `prefix_beta` in section `git`: 

`prefix_beta: "beta-lex-quote"`

I would expect that 'beta-lex-quote' is used for the prefix instead of 'beta' as shown in github url

Background: we changed packaging orgs a few times. Last time @jlantz suggested, we should simply change the beta tag.

**Comment by jlantz** [comment]
Hmm, that is indeed odd.  You can use `cci shell` to verify how the project config has been constructed.  In the shell, `config` is `cci`'s config instance and the project config is available as `config.project_config`.  You can access any element from the project config's dictionary as an attribute of project config using `__` (double underscore) to specify descending into the config tree.  So, you can check by running this in the shell: `config.project_config.project__git__prefix_beta`

One note is that you'll probably want a `/` on the end of the prefix.  The default prefix is `beta/` because we wanted to allow for formats like `beta-NN` if someone wanted it for some reason for their implementation.

You can see how we override `prefix_beta` here: https://github.com/SalesforceFoundation/Cumulus/blob/master/cumulusci.yml#L12

**Comment by jlantz** [comment]
Actually, this looks like a bug that we just hit ourselves trying to change the prefix_beta on one of our repositories for a temporary packaging org.  New release coming shortly.

**Comment by Szandor72** [comment]
Thank you very much, Jason!
