### ISSUE TITLE
Ability for task "update_dependencies" to use LATEST syntax to retrieve latest version of a managed package

### ISSUE THREAD

**Issue by Julian88Tex** [SalesforceFoundation/CumulusCI#597]
Would be nice if task `update_dependencies` could also use the same syntax as [Salesforce DX](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_dev2gp_config_keywords.htm?search_text=latest) to check for the latest version of a managed package.

```
    dependencies:
        - namespace: stayclassy
          version: LATEST
```

This helps prevent constantly needing to update the cumulusci.yml file if you are always testing with the latest version of another package.

**Comment by jlantz** [comment]
The challenge with this is that you'd need access to the packaging org for the stayclassy namespace in order to query for the latest version.  There's no public API that I'm aware of to query for the latest release of a managed package.  That's why we use Github Releases via the Github API to get the latest release by default in tasks like `install_managed` and `install_managed_beta`.

To install a package in DX, you need the PackageVersionId instead of just the namespace and version number.  The docs you linked to are instructions for setting up the version number of a packaging 2 package you're generating from your repository.

You can, however, automatically get the latest version of the dependency if you point at a Github repository that has releases created via the `cci task run github_release` command.  The github dependency type will automatically install the latest production release version.

Here's more info on the Github dependencies: http://cumulusci.readthedocs.io/en/latest/features.html#github-repository-dependencies

**Comment by Julian88Tex** [comment]
@jlantz I see makes sense! I didn't think about how SFDX was able to access that extra piece of info that's not possible when just installed a managed package. Thanks!
